### ISSUE TITLE
Stable docs broken again

### ISSUE THREAD

**Issue by JaylyDev** [JaylyDev/scriptapi-docs#8]
What happened?

![image](https://github.com/JaylyDev/scriptapi-docs/assets/65847850/63428f8c-10af-4696-9312-10058389a646)
![image](https://github.com/JaylyDev/scriptapi-docs/assets/65847850/d6779bad-3412-457a-97a0-ac736f755700)

**Comment by StealthyExpertX** [comment]
Yeah, we noticed it today when our team was doing another deep dive into the API, we noticed the website broke/is no longer working, we actively use this website, it's by far the best documentation format we've seen by anybody in the community.

**Comment by StealthyExpertX** [comment]
If you need any help with testing or debugging let us know!
